# Generated by Django 3.0.5 on 2020-04-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0005_auto_20200421_0351'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('products', models.ManyToManyField(blank=True, to='products.Product')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
