# Generated by Django 3.0.5 on 2020-04-21 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200421_0323'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Type',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='users',
        ),
        migrations.AlterModelTable(
            name='type',
            table='product_types',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
